# Generated by Django 3.2.6 on 2021-10-07 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文集',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='请输入标题，不超过128个字符', max_length=128)),
                ('body', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('e', '发表')], default='a', max_length=1, verbose_name='文章状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('thumb_up', models.IntegerField(default=0, verbose_name='点赞数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.articlecategory')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-views', '-pub_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
