# Generated by Django 3.2.6 on 2021-10-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb_up',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', '草稿'), ('e', '发表')], default='a', max_length=1, verbose_name='文章状态'),
        ),
    ]
