# Generated by Django 3.2.6 on 2021-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211023_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(default='static\\image\\avatar.jpeg', max_length=128, upload_to='static/image/head/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('1', '女'), ('2', '保密')], default='1', max_length=6, verbose_name='性别'),
        ),
    ]
