# Generated by Django 3.2.6 on 2021-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211023_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attention',
            old_name='B_follower',
            new_name='follower',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('2', '保密'), ('1', '女')], default='1', max_length=6, verbose_name='性别'),
        ),
    ]
