# Generated by Django 3.2.6 on 2021-10-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_auto_20211017_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praise_time', models.DateTimeField(auto_now=True, verbose_name='点赞时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.article', verbose_name='被点赞的文章')),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
        ),
    ]
