# Generated by Django 3.2.6 on 2021-11-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0002_complimentforcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complimentforcomment',
            options={},
        ),
        migrations.AlterModelTable(
            name='complimentforcomment',
            table='compliment_for_comment',
        ),
    ]
