# Generated by Django 3.2.6 on 2021-11-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('compliment', '0003_auto_20211104_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliment',
            name='praise_type',
            field=models.IntegerField(choices=[(1, '赞'), (0, '踩')], default=1, verbose_name='赞的类型'),
        ),
        migrations.AlterField(
            model_name='complimentforcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliment_comments', to='comment.comment', verbose_name='被点赞的文章'),
        ),
    ]
